### ISSUE TITLE
Lack of `SpaceDID` is raising an error in the current distribution

### ISSUE THREAD

**Issue by dysbulic** [web3-storage/w3cli#105]
I ran `npm install --global @web3-storage/w3cli` then `w3` and I get the error:
```
file://~/.nodenv/versions/20.5.0/lib/node_modules/@web3-storage/w3cli/node_modules/@web3-storage/upload-client/src/store.js:3
import { SpaceDID } from '@web3-storage/capabilities/utils'
         ^^^^^^^^
SyntaxError: The requested module '@web3-storage/capabilities/utils' does not provide an export named 'SpaceDID'
```
In looking into [the `@web3-storage/capabilities/utils` downloaded by `@web3-storage/w3cli`](https://www.npmjs.com/package/@web3-storage/capabilities?activeTab=code) it is indeed missing `SpaceDID`.

The blame says these changes were made three weeks ago & I think a new `@web3-storage/capabilities` needs to be published.

**Comment by gobengo** [comment]
@dysbulic I believe this has been fixed, and I am able to run `npm install --global @web3-storage/w3cli` and then `w3` without error. I expect you can no longer reproduce this. Is that right?

**Comment by gobengo** [comment]
@dysbulic I'm hoping this is resolved. Feel free to reopen with more info if you are still facing the issue.
