### ISSUE TITLE
`w3 authorize` should detect authz confirmation within 5 second time budget

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3cli#67]
Context:
* improving experience of https://github.com/web3-storage/w3cli/issues/46

Consider:
* measuring how often time budget is succeeded (or log warning in an ugly way that shames us into fixing it)

Solutions Considered
* try a method other than waiting for the /validate-ws websocket handled by access-api cloudflare worker
  * e.g. `expectNewClaimableDelegations` https://github.com/web3-storage/w3protocol/blob/main/packages/access-api/test/access-client-agent.test.js#L395
  * e.g. combinding methods via Promise.race https://github.com/web3-storage/w3protocol/pull/560
* adjust how the /validate-ws websocket works to be more faster
  * use techniques like what this did to improve websocket *but only for old voucher flow, not new flow* https://github.com/web3-storage/w3protocol/pull/449

**Comment by gobengo** [comment]
I'm hoping the work in https://github.com/web3-storage/w3protocol/pull/666 will help with this

**Comment by travis** [comment]
I believe this is fixed
