### ISSUE TITLE
Stand-alone CLI for bundling with apps

### ISSUE THREAD

**Issue by regcs** [web3-storage/w3cli#82]
Hi,

I am writing a (decentralized) Go app and I want to rely on w3up for file uploads from users. The app will either rely on one w3 space payed by me and delegated to users or each user will have its own space registered. 

However, there is no Go API for w3up. So I need to build a wrapper. For that, I would like to bundle my app with a stand-alone binary of the w3cli.

Since I did not succeed with compiling a stand-alone binary from this repository‘s code using `pkg` I wanted to ask here if that is possible in any other way? Did anyone do this before?

I would very much appreciate any help! 😊

**Comment by tas8876** [comment]
I'm facing the same problem. 
Any suggestions are welcome.
A golang impl would be awesome too.

**Comment by alanshaw** [comment]
Yes this is on our radar and we want to get this story figured out for the official launch. Will update here when there's some news.

**Comment by regcs** [comment]
Great, thanks for letting us know @alanshaw!

**Comment by regcs** [comment]
Hi, just checked back after some months now. the issue was marked as completed, by I am install unable to compile a standalone via `pkg`. Was that issue solved? If so, is there any instructions on how to do it?
